# Generated by Django 6.0.7 on 2026-07-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=250)),
                ('contact_email', models.EmailField(max_length=254)),
                ('urgent', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
